// RUN: waveasm-translate %s 2>&1 | FileCheck %s
//
// Test: dynamic shapes support — index-typed kernel arguments loaded from
// kernarg buffer, dynamic SRD buffer sizes, vector.store translation with
// dynamic stride address computation from memref.reinterpret_cast.
//
// This matches the MLIR pattern generated by the Wave compiler when M and N
// are dynamic symbols (not in subs).

// CHECK-LABEL: waveasm.program @dynamic_shapes_kernel

// Test 1: index args loaded from kernarg buffer via s_load_dword
// CHECK: waveasm.s_load_dword
// CHECK: waveasm.s_load_dword

// Test 2: SRD buffer size is max (0xFFFFFFFF) for dynamic memrefs
// CHECK: 0xFFFFFFFF

// Test 3: scalar args moved to VGPRs after SRD setup
// CHECK: v_mov_b32 v2
// CHECK: v_mov_b32 v3

// Test 4: dynamic stride address computation (runtime v_mul_lo_u32)
// CHECK: waveasm.v_mul_lo_u32
// CHECK: waveasm.v_mul_lo_u32

// Test 5: vector.store emits buffer_store
// CHECK: waveasm.buffer_store

module {
func.func @dynamic_shapes_kernel(
    %binding_a: !stream.binding,
    %binding_c: !stream.binding,
    %M: index,
    %N: index) {

  %c0 = arith.constant 0 : index

  %flat_a = "stream.binding.subspan"(%binding_a, %c0) : (!stream.binding, index) -> memref<f16>
  %flat_c = "stream.binding.subspan"(%binding_c, %c0) : (!stream.binding, index) -> memref<f32>

  // Reinterpret with dynamic sizes and static strides (input)
  %a = "memref.reinterpret_cast"(%flat_a, %M) <{
    operandSegmentSizes = array<i32: 1, 0, 1, 0>,
    static_offsets = array<i64: 0>,
    static_sizes = array<i64: -9223372036854775808, 128>,
    static_strides = array<i64: 128, 1>
  }> : (memref<f16>, index) -> memref<?x128xf16, strided<[128, 1]>>

  // Reinterpret with dynamic sizes AND dynamic stride (output)
  %c = "memref.reinterpret_cast"(%flat_c, %M, %N, %N) <{
    operandSegmentSizes = array<i32: 1, 0, 2, 1>,
    static_offsets = array<i64: 0>,
    static_sizes = array<i64: -9223372036854775808, -9223372036854775808>,
    static_strides = array<i64: -9223372036854775808, 1>
  }> : (memref<f32>, index, index, index) -> memref<?x?xf32, strided<[?, 1]>>

  %thread_id = "gpu.thread_id"() <{dimension = #gpu<dim x>, upper_bound = 64 : index}> : () -> index

  // Load from input
  %loaded = "vector.load"(%a, %thread_id, %c0) : (memref<?x128xf16, strided<[128, 1]>>, index, index) -> vector<1xf16>
  %ext = "arith.extf"(%loaded) : (vector<1xf16>) -> vector<1xf32>

  // Store with dynamic stride to output
  "vector.store"(%ext, %c, %thread_id, %c0) : (vector<1xf32>, memref<?x?xf32, strided<[?, 1]>>, index, index) -> ()

  return
}
}
